### PR TITLE
Add redirects for blog posts

### PR DESCRIPTION
**Pull request by NgariNdungu**
Uses [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) to redirect to changed post urls.
Avoids 404s when following links shared elsewhere.

### CODE REVIEW

**Comment by zegetech** [comment]
Also include fix for #33

**Comment by NgariNdungu** [comment]
> Also include fix for #33

I have added [jekyll-relative-links](https://github.com/benbalter/jekyll-relative-links) gem and edited the links in the posts. The gem will however not work for links in post front-matter(`intro`)

**Comment by zegetech** [comment]
@NgariNdungu  Static permalink already added in `_config.yml`, therefore not necessary to add the redirect-from functionality as the category is not in the link. Please only have relative links if possible

**Comment by NgariNdungu** [comment]
I am adding redirect-from for the links that were shared before the permalink was added. These point to `/news...` or `/developer...`. Following from twitter/facebook/whatsapp  will result in `404`s

**Pull request closed without merging**
